name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6

      - name: Create venv **and** sync deps   # one multi-line run block
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip sync requirements.lock

      - uses: pre-commit/action@v3.0.1
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest -q
